server:
  port: 8080
  servlet:
    context-path: /
  ssl:
    enabled: true
    key-alias: kebook_ssl_v2
    key-store: classpath:kebook-ssl_v2.p12
    key-store-type: PKCS12
    key-password: kebook
    key-store-password: kebook